apps:
    - name: 'sveltekit-app'              # Name of your app
      script: 'build/index.js'            # Path to the built app's entry point
      instances: 1                        # Number of instances to run
      exec_mode: 'fork'                # Enable cluster mode
      env:                                # Environment variables
          NODE_ENV: 'production'            # Set environment to production
      env_development:                    # Environment for development
          NODE_ENV: 'development'
