name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.6.0  # Updated to v3.6.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0  # Updated to v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/prain-app:latest -f docker/Dockerfile .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/prain-app:latest

  restart:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - name: Restart Azure Web App
        run: |
          az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
          az webapp restart --name $(terraform output -raw app_service_name) --resource-group sveltekit-rg
